### ISSUE TITLE
Hunter pretending to be a Titan Arc melee build

### ISSUE THREAD

**Issue by alexlblount** [PhantomsChosen/build-profiles#16]
Hunter arc melee build to pretend you're a punch happy titan.

Use Liar's Handshake or Assassin's cowl along with some well and CWL mods to buff damage and defense.

Liar's Handshake has the added benefit of being able to stun lock some beefy enemies.

**Comment by cuzelac** [comment]
I really like Liar's Handshake build so I'll do this one now

**Comment by cuzelac** [comment]
https://github.com/PhantomsChosen/build-profiles/pull/20
